<?php

/*
 *
 * Switchbox
 *
 * Copyright (C) 2017 LegendsOfMCPE Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
*/


namespace switchbox\api\economy;


use switchbox\api\SwitchQuery;

class BalanceQuery extends SwitchQuery {

	public $param_playerName;
	public $param_account;

	public $balance;

	/**
	 * Checks the balance of an account.
	 *
	 * @param string        $playerName the player owning the account
	 * @param string|null   $account    the name of the account to check, or null to use the default account
	 * @param callable|null $callback
	 */
	public function __construct(string $playerName, string $account = null, callable $callback = null) {
		parent::__construct($callback);
		$this->param_playerName = $playerName;
		$this->param_account = $account;
	}

	/**
	 * The balance of the queried account
	 *
	 * @return float
	 */
	public function getBalance(): float {
		return $this->balance;
	}

	protected function mustHandle(): bool {
		return parent::mustHandle(); // TODO: Change the autogenerated stub
	}
}
